<script src="<?php echo e(URL::asset('front/assets/js/jquery.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/waypoints.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/bootstrap.bundle.min.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/swiper-bundle.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/slick.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/magnific-popup.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/counterup.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/wow.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/meanmenu.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/isotope-pkgd.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/imagesloaded-pkgd.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/charming.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/hover-reveal.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/tween-max.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/ajax-form.js')); ?>"></script>
<script src="<?php echo e(URL::asset('front/assets/js/main.js')); ?>"></script>
<?php /**PATH D:\Work\tekinity\tekinity-business-old\resources\views/front/layouts/partials/js.blade.php ENDPATH**/ ?>